mqtt:
  host: broker_mqtt
  port: 1883
detectors:
  cpu1:
    type: cpu
cameras:
  camera_idoso:
    ffmpeg:
      inputs:
        - path: rtsp://{CAMERA_USER}:{CAMERA_PASS}@{CAMERA_HOST}:{CAMERA_PORT}/{CAMERA_ENDPOINT}
          roles:
            - detect
        - path: rtsp://{CAMERA_USER}:{CAMERA_PASS}@{CAMERA_HOST}:{CAMERA_PORT}/{CAMERA_ENDPOINT}
          roles:
            - record
    detect:
      enabled: true
      fps: 5
      width: 640
      height: 360
    objects:
      track:
        - person
    record:
      enabled: true
      continuous:
        days: 7
    snapshots:
      enabled: true
version: 0.17-0
