mqtt:
  host: broker_mqtt
  port: 1883

detectors:
  cpu1:
    type: cpu

snapshots:
  enabled: true
  retain:
    default: 3

record:
  enabled: true

cameras:
  camera_idoso:
    ffmpeg:
      inputs:
        - path: rtsp://{CAMERA_USER}:{CAMERA_PASS}@{CAMERA_HOST}:{CAMERA_PORT}/{CAMERA_ENDPOINT}
          roles:
            - detect
            - record
    detect:
      enabled: true
      fps: 5
      width: 640
      height: 360
    objects:
      track:
        - person

version: 0.17-0
